// c-api-examples/moss-tts-c-api.c
//
// Copyright (c)  2026  zengyw

// This file shows how to use sherpa-onnx C API
// for zero-shot TTS with MOSS.
//
// clang-format off
/*
Usage

Run ./scripts/moss-tts-nano/run.sh to export the MOSS model folder, then run:

cd ./scripts/moss-tts-nano
../../build-moss-tts-nano-shared/bin/moss-tts-c-api
../../build-moss-tts-nano-shared/bin/moss-tts-c-api './matcha-icefall-zh-baker/phone.fst,./matcha-icefall-zh-baker/date.fst,./matcha-icefall-zh-baker/number.fst'

*/
// clang-format on

#include <stdio.h>
#include <string.h>

#include "sherpa-onnx/c-api/c-api.h"

static int32_t ProgressCallback(const float* samples, int32_t num_samples,
                                float progress, void* arg) {
  fprintf(stderr, "Progress: %.3f%%\n", progress * 100);
  // return 1 to continue generating
  // return 0 to stop generating
  return 1;
}

int32_t main(int32_t argc, char* argv[]) {
  SherpaOnnxOfflineTtsConfig config;
  memset(&config, 0, sizeof(config));

  config.model.moss.prefill =
      "./sherpa-onnx-moss-tts-nano-2026-05-07/moss_tts_prefill.onnx";
  config.model.moss.decode_step =
      "./sherpa-onnx-moss-tts-nano-2026-05-07/moss_tts_decode_step.onnx";
  config.model.moss.local_fixed_sampled_frame =
      "./sherpa-onnx-moss-tts-nano-2026-05-07/"
      "moss_tts_local_fixed_sampled_frame.onnx";
  config.model.moss.codec_encoder =
      "./sherpa-onnx-moss-tts-nano-2026-05-07/"
      "moss_audio_tokenizer_encode.onnx";
  config.model.moss.codec_decoder =
      "./sherpa-onnx-moss-tts-nano-2026-05-07/"
      "moss_audio_tokenizer_decode_full.onnx";
  config.model.moss.tokenizer_vocab =
      "./sherpa-onnx-moss-tts-nano-2026-05-07/tokenizer_vocab.json";
  config.model.moss.tokenizer_scores =
      "./sherpa-onnx-moss-tts-nano-2026-05-07/tokenizer_scores.json";

  if (argc > 1 && argv[1] && argv[1][0]) {
    config.rule_fsts = argv[1];
  }

  config.model.num_threads = 2;

  // If you don't want to see debug messages, please set it to 0
  config.model.debug = 1;
  const char* filename = "./generated-moss-c.wav";
  const char* text =
      "中英文语音合成测试。This is generated by next generation Kaldi using "
      "MOSS tts nano. 你觉得中英文说的如何呢？";

  const SherpaOnnxOfflineTts* tts = SherpaOnnxCreateOfflineTts(&config);
  if (!tts) {
    fprintf(stderr, "Error create Offline TTS\n");
    return -1;
  }

  SherpaOnnxGenerationConfig cfg = {0};
  const char* prompt_audio_file =
      "./sherpa-onnx-moss-tts-nano-2026-05-07/prompt_wavs/zh_1.wav";
  const SherpaOnnxWave* wave = SherpaOnnxReadWave(prompt_audio_file);
  if (!wave) {
    fprintf(stderr, "Failed to read %s\n", prompt_audio_file);
    SherpaOnnxDestroyOfflineTts(tts);
    return -1;
  }
  cfg.reference_audio = wave->samples;
  cfg.reference_audio_len = wave->num_samples;
  cfg.reference_sample_rate = wave->sample_rate;
  cfg.extra = "{\"max_new_frames\": 375, \"seed\": 42}";

  const SherpaOnnxGeneratedAudio* audio =
      SherpaOnnxOfflineTtsGenerateWithConfig(tts, text, &cfg, ProgressCallback,
                                             NULL);

  SherpaOnnxFreeWave(wave);

  fprintf(stderr, "Input text is: %s\n", text);

  if (audio) {
    SherpaOnnxWriteWave(audio->samples, audio->n, audio->sample_rate, filename);
    fprintf(stderr, "Saved to: %s\n", filename);
    SherpaOnnxDestroyOfflineTtsGeneratedAudio(audio);
  }

  SherpaOnnxDestroyOfflineTts(tts);

  return 0;
}
