#!/usr/bin/env python3
#
# Copyright (c)  2026  zengyw

"""
This file demonstrates how to use sherpa-onnx Python API
for zero-shot TTS with MOSS.

Usage:

Run ./scripts/moss-tts-nano/run.sh to export the MOSS model folder, then run:

cd ./scripts/moss-tts-nano
python3 ../../python-api-examples/moss-tts.py
python3 ../../python-api-examples/moss-tts.py './matcha-icefall-zh-baker/phone.fst,./matcha-icefall-zh-baker/date.fst,./matcha-icefall-zh-baker/number.fst'

"""

import sys
import time

import sherpa_onnx
import soundfile as sf


def create_tts(rule_fsts=""):
    model_dir = "./sherpa-onnx-moss-tts-nano-2026-05-07"
    tts_config = sherpa_onnx.OfflineTtsConfig(
        model=sherpa_onnx.OfflineTtsModelConfig(
            moss=sherpa_onnx.OfflineTtsMossModelConfig(
                prefill=f"{model_dir}/moss_tts_prefill.onnx",
                decode_step=f"{model_dir}/moss_tts_decode_step.onnx",
                local_fixed_sampled_frame=(
                    f"{model_dir}/moss_tts_local_fixed_sampled_frame.onnx"
                ),
                codec_encoder=f"{model_dir}/moss_audio_tokenizer_encode.onnx",
                codec_decoder=f"{model_dir}/moss_audio_tokenizer_decode_full.onnx",
                tokenizer_vocab=f"{model_dir}/tokenizer_vocab.json",
                tokenizer_scores=f"{model_dir}/tokenizer_scores.json",
            ),
            debug=True,
            num_threads=2,
            provider="cpu",
        ),
        rule_fsts=rule_fsts,
    )
    if not tts_config.validate():
        raise ValueError(
            "Please read the previous error messages and re-check your config"
        )

    return sherpa_onnx.OfflineTts(tts_config)


def main():
    rule_fsts = sys.argv[1] if len(sys.argv) > 1 else ""
    tts = create_tts(rule_fsts)

    text = (
        "中英文语音合成测试。This is generated by next generation Kaldi using "
        "MOSS tts nano. 你觉得中英文说的如何呢？"
    )

    gen_config = sherpa_onnx.GenerationConfig()
    prompt_audio_file = (
        "./sherpa-onnx-moss-tts-nano-2026-05-07/prompt_wavs/zh_1.wav"
    )
    prompt_audio, prompt_sample_rate = sf.read(
        prompt_audio_file, dtype="float32", always_2d=False
    )
    if prompt_audio.ndim > 1:
        prompt_audio = prompt_audio[:, 0]
    gen_config.reference_audio = prompt_audio
    gen_config.reference_sample_rate = prompt_sample_rate
    gen_config.extra["max_new_frames"] = "375"
    gen_config.extra["seed"] = "42"

    start = time.time()
    audio = tts.generate(text, gen_config)
    end = time.time()

    if len(audio.samples) == 0:
        print("Error in generating audios. Please read previous error messages.")
        return

    elapsed_seconds = end - start
    audio_duration = len(audio.samples) / audio.sample_rate
    real_time_factor = elapsed_seconds / audio_duration

    output_filename = "./generated-moss-python.wav"
    sf.write(
        output_filename,
        audio.samples,
        samplerate=audio.sample_rate,
        subtype="PCM_16",
    )
    print(f"Saved to {output_filename}")
    print(f"The text is '{text}'")
    print(f"Elapsed seconds: {elapsed_seconds:.3f}")
    print(f"Audio duration in seconds: {audio_duration:.3f}")
    print(f"RTF: {elapsed_seconds:.3f}/{audio_duration:.3f} = {real_time_factor:.3f}")


if __name__ == "__main__":
    main()
