// cxx-api-examples/moss-tts-cxx-api.cc
//
// Copyright (c)  2026  zengyw

// This file shows how to use sherpa-onnx CXX API
// for zero-shot TTS with MOSS.
//
// clang-format off
/*
Usage

Run ./scripts/moss-tts-nano/run.sh to export the MOSS model folder, then run:

cd ./scripts/moss-tts-nano
../../build-moss-tts-nano-shared/bin/moss-tts-cxx-api
../../build-moss-tts-nano-shared/bin/moss-tts-cxx-api './matcha-icefall-zh-baker/phone.fst,./matcha-icefall-zh-baker/date.fst,./matcha-icefall-zh-baker/number.fst'

*/
// clang-format on

#include <cstdint>
#include <cstdio>
#include <string>
#include <utility>

#include "sherpa-onnx/c-api/cxx-api.h"

static int32_t ProgressCallback(const float *samples, int32_t num_samples,
                                float progress, void *arg) {
  fprintf(stderr, "Progress: %.3f%%\n", progress * 100);
  // return 1 to continue generating
  // return 0 to stop generating
  return 1;
}

int32_t main(int32_t argc, char *argv[]) {
  using namespace sherpa_onnx::cxx;  // NOLINT

  OfflineTtsConfig config;
  config.model.moss.prefill =
      "./sherpa-onnx-moss-tts-nano-2026-05-07/moss_tts_prefill.onnx";
  config.model.moss.decode_step =
      "./sherpa-onnx-moss-tts-nano-2026-05-07/moss_tts_decode_step.onnx";
  config.model.moss.local_fixed_sampled_frame =
      "./sherpa-onnx-moss-tts-nano-2026-05-07/"
      "moss_tts_local_fixed_sampled_frame.onnx";
  config.model.moss.codec_encoder =
      "./sherpa-onnx-moss-tts-nano-2026-05-07/"
      "moss_audio_tokenizer_encode.onnx";
  config.model.moss.codec_decoder =
      "./sherpa-onnx-moss-tts-nano-2026-05-07/"
      "moss_audio_tokenizer_decode_full.onnx";
  config.model.moss.tokenizer_vocab =
      "./sherpa-onnx-moss-tts-nano-2026-05-07/tokenizer_vocab.json";
  config.model.moss.tokenizer_scores =
      "./sherpa-onnx-moss-tts-nano-2026-05-07/tokenizer_scores.json";

  if (argc > 1 && argv[1] && argv[1][0]) {
    config.rule_fsts = argv[1];
  }

  config.model.num_threads = 2;

  // If you don't want to see debug messages, please set it to 0
  config.model.debug = 1;
  std::string filename = "./generated-moss-cxx.wav";
  std::string text =
      "中英文语音合成测试。This is generated by next generation Kaldi using "
      "MOSS tts nano. 你觉得中英文说的如何呢？";

  auto tts = OfflineTts::Create(config);

  GenerationConfig gen_config;
  std::string prompt_audio_file =
      "./sherpa-onnx-moss-tts-nano-2026-05-07/prompt_wavs/zh_1.wav";
  Wave wave = ReadWave(prompt_audio_file);
  gen_config.reference_audio = std::move(wave.samples);
  gen_config.reference_sample_rate = wave.sample_rate;
  gen_config.extra["max_new_frames"] = "375";
  gen_config.extra["seed"] = "42";

  GeneratedAudio audio = tts.Generate(text, gen_config, ProgressCallback);

  WriteWave(filename, {audio.samples, audio.sample_rate});

  fprintf(stderr, "Input text is: %s\n", text.c_str());
  fprintf(stderr, "Saved to: %s\n", filename.c_str());

  return 0;
}
